#!/bin/sh

CFLAGS="-Wall -Wextra -Wshadow -Werror -Werror=unused-result -g3 -std=gnu11 -pedantic -O2"
clear
set -xe
rm callgrind.out.*
gcc $OPT $CFLAGS -o $1 $1.c && valgrind --tool=callgrind ./$1 --dump-instr=yes --collect-jumps=yes <<< $(< ./open_testcases/$2.txt)
