#!/bin/sh

CFLAGS="-Wall -Wextra -Wshadow -Werror -Werror=unused-result -std=gnu11 -pedantic -ggdb"
clear
if [ -z $3 ]; then
  OPT="";
else
  OPT="-D DEBUG";
fi
set -xe
gcc $OPT $CFLAGS -o $1 $1.c && time ./$1 <<< $(< ./open_testcases/$2.txt)
